/* Test-only fixtures run on 8771; production 8770 is only read, never mutated. */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'playwright');
const root = path.resolve(__dirname, '..');
const shots = path.join(root, '.impeccable', 'review');
fs.mkdirSync(shots, { recursive: true });

(async () => {
  const browser = await chromium.launch({ headless: true, channel: 'chrome' });
  const context = await browser.newContext({ viewport: { width: 1536, height: 1024 }, reducedMotion: 'reduce' });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  const ready = async () => { await page.getByRole('heading', { name: '고객·주문 정보', exact: true }).waitFor(); await page.evaluate(() => document.fonts.ready); };
  await page.goto('http://127.0.0.1:8770/');
  await ready();
  assert(await page.getByText('의류 쇼핑몰 데모 · 외부 발송 없음').isVisible());
  assert.equal(await page.locator('meter').count(), 0);
  assert(!(await page.locator('.inquiry-panel').innerText()).includes('데모 문의'));
  assert((await page.locator('.customer-facts').innerText()).includes('주문 상품'));
  await page.evaluate(() => { window.scrollTo(0, 0); document.activeElement?.blur(); });
  await page.screenshot({ path: path.join(shots, 'hero-repro.png') });
  await page.evaluate(() => { window.scrollTo(0, 0); document.activeElement?.blur(); });
  await page.screenshot({ path: path.join(shots, 'desktop.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.evaluate(() => { window.scrollTo(0, 0); document.activeElement?.blur(); });
  await page.screenshot({ path: path.join(shots, 'mobile.png'), fullPage: true });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'mobile overflow');
  await page.setViewportSize({ width: 1536, height: 1024 });
  await page.goto('http://127.0.0.1:8771/');
  await ready();
  const firstDraftRequests = [];
  page.on('request', request => { if (request.method() === 'POST' && request.url().endsWith('/draft')) firstDraftRequests.push(request.url()); });
  const nextPoll = () => page.waitForResponse(response => response.url().endsWith('/api/status') && response.request().method() === 'GET');
  const settleAutomatic = async () => {
    await page.waitForFunction(async () => {
      const response = await fetch('/api/status');
      const result = await response.json();
      return result.auto_draft.queued === 0 && result.auto_draft.running === 0;
    });
    await nextPoll();
  };
  assert.equal(await page.getByRole('button', { name: 'AI 초안 작성', exact: true }).count(), 0);
  assert((await page.locator('.answer-panel').innerText()).includes('완료되면 대기 중인 문의를 자동으로 처리합니다.'));
  const firstAction = await page.getByRole('button', { name: '승인하고 기록', exact: true }).boundingBox();
  assert(firstAction.y >= 0 && firstAction.y + firstAction.height <= 1024, 'desktop review action visible without scrolling');
  const firstEditor = await page.getByRole('textbox', { name: '답변 내용', exact: true }).boundingBox();
  assert(firstEditor.y < firstAction.y, 'answer area and action share the first desktop viewport');
  await page.getByRole('button', { name: 'FAQ 자료', exact: true }).click();
  await page.getByRole('button', { name: '검색 색인 만들기', exact: true }).click();
  await page.getByText('검색 색인을 갱신했습니다. 대기 중인 문의의 초안을 자동으로 작성합니다.').waitFor();
  await page.getByRole('button', { name: '문의함', exact: true }).click();
  await page.getByRole('button', { name: '승인하고 기록', exact: true }).waitFor();
  await page.waitForFunction(() => document.querySelector('[aria-label="답변 내용"]')?.value.includes('브라우저 테스트용'));
  await settleAutomatic();
  const seeded = await context.request.get('http://127.0.0.1:8771/api/tickets').then(response => response.json());
  assert.equal(seeded.tickets.length, 8);
  assert(seeded.tickets.every(ticket => ticket.draft && ticket.auto_draft.state === 'completed'), 'all seeded inquiries get a first draft, including unselected ones');
  assert.deepEqual(firstDraftRequests, [], 'browser never posts an initial draft request');
  await page.evaluate(() => { window.scrollTo(0, 0); document.activeElement?.blur(); });
  await page.screenshot({ path: path.join(shots, 'desktop-draft-fixture.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.evaluate(() => { window.scrollTo(0, 0); document.activeElement?.blur(); });
  await page.screenshot({ path: path.join(shots, 'mobile-draft-fixture.png'), fullPage: true });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'draft mobile overflow');
  await page.setViewportSize({ width: 1536, height: 1024 });
  const editor = page.getByRole('textbox', { name: '답변 내용', exact: true });
  const currentAnswer = '[모의 테스트] 상담원이 첨삭 중인 답변입니다.';
  const direction = '사과 표현을 넣고 해결 절차부터 짧게 설명';
  await editor.fill(currentAnswer);
  await page.getByRole('button', { name: '재생성', exact: true }).click();
  const guidance = page.getByLabel('재생성 방향 (선택)', { exact: true });
  await guidance.fill(direction);
  assert.equal(await guidance.getAttribute('maxlength'), '1000');
  await nextPoll(); await nextPoll();
  assert.equal(await editor.inputValue(), currentAnswer, 'read-only polling preserves human edits');
  assert.equal(await guidance.inputValue(), direction, 'read-only polling preserves regeneration direction');
  await page.evaluate(() => { window.scrollTo(0, 0); document.activeElement?.blur(); });
  await page.screenshot({ path: path.join(shots, 'desktop-regeneration.png'), fullPage: true });
  await page.locator('.answer-panel').screenshot({ path: path.join(shots, 'desktop-regeneration-detail.png') });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.evaluate(() => { window.scrollTo(0, 0); document.activeElement?.blur(); });
  await page.screenshot({ path: path.join(shots, 'mobile-regeneration.png'), fullPage: true });
  await page.locator('.regenerate-form').screenshot({ path: path.join(shots, 'mobile-regeneration-detail.png') });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'regeneration mobile overflow');
  await page.setViewportSize({ width: 1536, height: 1024 });
  let releaseFailure;
  const holdFailure = new Promise(resolve => { releaseFailure = resolve; });
  await page.route('**/api/tickets/*/draft', async route => {
    await holdFailure;
    await route.fulfill({ status: 502, contentType: 'application/json', body: JSON.stringify({ detail: '재생성 모의 오류입니다. 다시 시도해 주세요.' }) });
  });
  const failedRequest = page.waitForRequest(request => request.url().endsWith('/draft'));
  await page.getByRole('button', { name: '답변 재생성', exact: true }).click();
  const sent = (await failedRequest).postDataJSON();
  assert.equal(sent.guidance, direction);
  assert.equal(sent.current_answer, currentAnswer);
  assert(await editor.isDisabled(), 'editor cannot change while regeneration is pending');
  assert.equal(await editor.inputValue(), currentAnswer, 'pending regeneration preserves current text');
  assert(await page.locator('.regenerate-form').getByRole('status').isVisible(), 'pending feedback beside regeneration control');
  assert(await page.locator('.regenerate-form').getByRole('status').textContent().then(text => text.includes('다시 작성')));
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('.regenerate-form').screenshot({ path: path.join(shots, 'mobile-regeneration-pending.png') });
  releaseFailure();
  await page.getByRole('alert').filter({ hasText: '재생성 모의 오류' }).waitFor();
  assert((await page.locator('.regenerate-form').getByRole('status').textContent()).includes('현재 답변과 입력한 방향은 유지됩니다.'));
  assert.equal(await editor.inputValue(), currentAnswer, 'failure preserves human edits');
  assert.equal(await guidance.inputValue(), direction, 'failure preserves regeneration direction');
  await page.locator('.regenerate-form').screenshot({ path: path.join(shots, 'mobile-regeneration-error.png') });
  await page.setViewportSize({ width: 1536, height: 1024 });
  await page.locator('.regenerate-form').screenshot({ path: path.join(shots, 'desktop-regeneration-error.png') });
  await page.unroute('**/api/tickets/*/draft');
  await page.getByRole('button', { name: '답변 재생성', exact: true }).click();
  await page.getByText('재생성 결과로 교체했습니다. 답변과 원문 근거를 검토해 주세요.').waitFor();
  assert.equal(await editor.inputValue(), `[브라우저 테스트용 재생성] 입력 방향: ${direction}\n수정 전 답변: ${currentAnswer}`);
  assert.equal(await guidance.count(), 0, 'successful regeneration closes direction form');
  await page.reload(); await ready();
  assert((await editor.inputValue()).startsWith('[브라우저 테스트용 재생성]'), 'regenerated answer persists after reload');
  await page.getByRole('textbox', { name: '답변 내용', exact: true }).fill('[모의 테스트] 검토 후 수정한 답변입니다.');
  page.once('dialog', dialog => dialog.dismiss());
  await page.getByRole('button', { name: 'FAQ 자료', exact: true }).click();
  assert.equal(await page.getByRole('textbox', { name: '답변 내용', exact: true }).inputValue(), '[모의 테스트] 검토 후 수정한 답변입니다.');
  await page.getByRole('button', { name: '승인하고 기록', exact: true }).click();
  await page.getByText('승인 내용을 로컬에 기록했습니다. 고객에게 발송하지 않았습니다.').waitFor();
  assert.equal(await page.getByRole('textbox', { name: '기록한 내용', exact: true }).inputValue(), '[모의 테스트] 검토 후 수정한 답변입니다.');
  await page.reload(); await ready();
  assert.equal(await page.getByRole('textbox', { name: '기록한 내용', exact: true }).inputValue(), '[모의 테스트] 검토 후 수정한 답변입니다.');
  await page.getByRole('button', { name: '설정', exact: true }).click();
  const fakeKey = 'test-only-not-a-real-gemini-key';
  await page.getByLabel('새 API 키').fill(fakeKey);
  await page.getByRole('button', { name: '키 저장', exact: true }).click();
  await page.getByText('키를 저장했습니다. 최신 검색 색인이 있으면 대기 문의를 자동으로 처리합니다.').waitFor();
  assert.equal(await page.getByLabel('새 API 키').inputValue(), '');
  assert.equal(await page.evaluate(() => localStorage.length + sessionStorage.length), 0);
  await page.evaluate(() => { window.scrollTo(0, 0); document.activeElement?.blur(); });
  await page.screenshot({ path: path.join(shots, 'settings.png'), fullPage: true });
  await page.getByRole('button', { name: '문의함', exact: true }).click();
  await page.getByRole('button', { name: '문의 접수', exact: true }).click();
  await page.getByLabel('문의 제목').fill('자동화 검사 문의');
  await page.getByLabel('문의 내용').fill('<img src=x onerror=alert(1)> 문자열은 실행되지 않아야 합니다.');
  const customerId = seeded.tickets[0].customer_id;
  await context.request.post('http://127.0.0.1:8771/api/tickets', { data: { customer_id: customerId, subject: '백그라운드 접수 검사', body: '현재 접수 화면을 쓰는 동안에도 이 문의의 초안이 작성되어야 합니다.' } });
  await nextPoll(); await nextPoll();
  assert.equal(await page.getByLabel('문의 제목').inputValue(), '자동화 검사 문의', 'background completion preserves new inquiry title');
  assert.equal(await page.getByLabel('문의 내용').inputValue(), '<img src=x onerror=alert(1)> 문자열은 실행되지 않아야 합니다.', 'background completion preserves new inquiry body');
  const regenerationCount = firstDraftRequests.length;
  await page.getByRole('button', { name: '문의 접수', exact: true }).click();
  await page.getByRole('heading', { name: '자동화 검사 문의', exact: true }).waitFor();
  assert.equal(await page.locator('.inquiry-panel img').count(), 0);
  await page.waitForFunction(() => document.querySelector('[aria-label="답변 내용"]')?.value.includes('브라우저 테스트용'));
  assert.equal(firstDraftRequests.length, regenerationCount, 'new inquiry also needs no browser draft call');
  await page.getByRole('button', { name: '문의 접수', exact: true }).click();
  await page.getByLabel('문의 제목').fill('초안 실패 검사');
  await page.getByLabel('문의 내용').fill('자동 초안 오류가 발생하면 재시도할 수 있어야 합니다.');
  await page.getByRole('button', { name: '문의 접수', exact: true }).click();
  await page.getByRole('button', { name: '초안 재시도', exact: true }).waitFor();
  assert((await page.locator('.answer-panel').innerText()).includes('초안을 작성하지 못했습니다.'));
  assert.equal(await editor.inputValue(), '', 'failed initial draft does not fabricate an answer');
  await page.getByRole('button', { name: '초안 재시도', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('[aria-label="답변 내용"]')?.value.includes('브라우저 테스트용'));
  assert.equal(firstDraftRequests.length, regenerationCount, 'retry only requeues work, never posts manual draft');
  await page.getByRole('button', { name: 'FAQ 자료', exact: true }).click();
  await page.locator('.doc-row').first().click();
  const content = page.getByLabel('FAQ 내용');
  await content.fill((await content.inputValue()) + '\n브라우저 검사에서 수정한 가상의 규정입니다.');
  const unsavedFaq = await content.inputValue();
  await context.request.post('http://127.0.0.1:8771/api/tickets', { data: { customer_id: customerId, subject: '백그라운드 FAQ 편집 검사', body: 'FAQ 편집 화면에서도 접수된 문의의 1차 초안은 자동으로 작성해야 합니다.' } });
  await nextPoll(); await nextPoll();
  assert.equal(await content.inputValue(), unsavedFaq, 'background completion preserves unsaved FAQ edits');
  page.once('dialog', dialog => dialog.dismiss());
  await page.getByRole('button', { name: '문의함', exact: true }).click();
  assert(await content.isVisible(), 'unsaved policy edit should survive cancelled navigation');
  await page.getByRole('button', { name: '문서 저장', exact: true }).click();
  await page.getByText('문서를 저장했습니다. 검색 색인을 다시 만들어 주세요.').waitFor();
  await page.evaluate(() => { window.scrollTo(0, 0); document.activeElement?.blur(); });
  await page.screenshot({ path: path.join(shots, 'knowledge.png'), fullPage: true });
  await page.getByRole('button', { name: '문의함', exact: true }).click();
  assert(await page.getByRole('button', { name: '승인하고 기록', exact: true }).isDisabled());
  await page.getByRole('button', { name: '담당자 이관', exact: true }).click();
  await page.getByLabel('이관 사유').fill('정책 변경 후 담당자 확인이 필요한 모의 테스트입니다.');
  await page.getByRole('button', { name: '이관 내용 기록', exact: true }).click();
  await page.getByText('담당자 이관 내용을 로컬에 기록했습니다. 외부 알림은 보내지 않았습니다.').waitFor();
  await page.getByRole('textbox', { name: '문의 검색', exact: true }).fill('일치할수없는검색어12345');
  assert(await page.getByText('검색 조건에 맞는 문의가 없습니다.').isVisible());
  await page.getByRole('textbox', { name: '문의 검색', exact: true }).fill('');
  await page.route('**/api/documents', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ detail: '모의 서버 오류입니다. 다시 시도해 주세요.' }) }));
  await page.reload();
  await page.getByRole('alert').waitFor();
  assert(await page.getByRole('button', { name: '다시 불러오기', exact: true }).isVisible());
  await page.unroute('**/api/documents');
  await page.getByRole('button', { name: '다시 불러오기', exact: true }).click();
  await ready();
  const unexpectedErrors = errors.filter(error => !error.includes('503 (Service Unavailable)') && !error.includes('502 (Bad Gateway)'));
  assert.deepEqual(unexpectedErrors, []);
  console.log(JSON.stringify({ result: 'pass', liveGemini: false, productionMutations: false, checks: ['responsive', 'index', 'all-inquiries-auto-first-draft', 'new-inquiry-auto-draft', 'no-browser-first-draft-request', 'auto-draft-failure-retry', 'poll-preserves-answer-guidance-and-forms', 'guided-regeneration', 'edited-answer-context', 'regeneration-failure-preserves-input', 'regeneration-persistence', 'edit', 'approve', 'reload', 'key-not-returned', 'create', 'literal-untrusted-text', 'policy-invalidates-draft', 'escalate', 'empty-search', 'server-error-recovery'], screenshots: shots }));
  await browser.close();
})().catch(error => { console.error(error); process.exit(1); });
